version: '3.7'
services:


  # nginx service
  web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "8082:80"
    volumes:
      - ./app/conf.d:/etc/nginx/conf.d
    networks:
      - custom

  # application service
  app:
    container_name: "app"
    image: app
    environment:
      - MONGODB_URL=mongodb://mongo_db/test_database
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres_db:5432/test_database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
    depends_on:
      - mongo_db
      - postgres_db


  # database service
  mongo_db:
    image: mongo
    container_name: "mongo_db"
    ports:
      - "27017:27017"
    networks:
      - custom

  # postgres service
  postgres_db:
    image: postgres:11
    container_name: 'postgres_db'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_database
    networks:
      - custom

  #pgadmin service
  pgadmin:
    container_name: 'pgadmin'
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - postgres_db
    networks:
      - custom

networks:
  custom:
    driver: bridge